# TODO: add test matrix for all SOM VMs
language: python

python:
  - "2.7"

install:
  - sudo apt-get install libc6-dev-i386
  - git clone --depth 1 https://github.com/smarr/PySOM.git
  - git clone --depth 1 https://github.com/smarr/som-java.git
  - git clone --depth 1 https://github.com/smarr/CSOM.git

# command to run tests
script:
  # Run unit tests with PySOM
  - cd PySOM && git --no-pager log -n 1 && ./som.sh -cp ../Smalltalk ../TestSuite/TestHarness.som
  - cd ..
  - cd som-java && git --no-pager log -n 1 && ant jar && ./som.sh -cp ../Smalltalk ../TestSuite/TestHarness.som
  - cd ..
  - cd CSOM && git --no-pager log -n 1 && make && cp Smalltalk/SOMCore.csp ../Smalltalk && ./som.sh -cp ../Smalltalk ../TestSuite/TestHarness.som

